import { NextPage } from "next";
import { useState } from "react";
import useHandleInput from "@hooks/useHandleInput";
import style from "@styles/components/Mypage.module.scss";
import Button from "@components/atomic/Button";
import Input from "@components/atomic/Input";
import { useAppDispatch, useAppSelector } from "@store/store";
import { editUserName, removeUserName } from "@store/userNameSlice";
import { USER_NAME } from "util/constant/query.constant";
import Head from "next/head";

const MyPage: NextPage = () => {
  const userName = useAppSelector((state) => state.userName.value);
  const dispatch = useAppDispatch();

  const [active, setActive] = useState(false);
  const {
    value: editName,
    onChange: onEditNameChange,
    setValue: setEditName,
  } = useHandleInput(userName);

  const handleAllContentsDelete = () => {
    const checkUSer = confirm(
      "전체 삭제를 하시면 모든 내용과 설정한 닉네임이 모두 사라집니다. 그래도 삭제하시겠습니까?"
    );
    if (checkUSer) {
      dispatch(removeUserName());
      localStorage.clear();
    } else {
      return false;
    }
  };

  const handleEditUserName = () => {
    dispatch(editUserName(editName));
    localStorage.setItem(USER_NAME, editName);
    setActive(false);
  };

  return (
    <>
      <Head>
        <title>돼지는 여행 중 : MyPage</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          href={`${process.env.NEXT_PUBLIC_FAVICON}/favicon.ico`}
        />
      </Head>
      <div className={style.mypage_container}>
        <h1>회원정보</h1>
        <div className={style.mypage_box}>
          <div className={style.mypage_item}>
            {active ? (
              <>
                <Input
                  type="text"
                  name="username"
                  value={editName}
                  onChange={onEditNameChange}
                  required={true}
                  labelText="별명 변경"
                />
                <Button
                  text="수정"
                  type="button"
                  large={false}
                  onClick={handleEditUserName}
                />
                <Button
                  text="취소"
                  type="button"
                  large={false}
                  onClick={() => setActive(false)}
                />
              </>
            ) : (
              <>
                <p className={style.mypage_p}>
                  별명
                  <span className={style.mypage_span}>{userName}</span>
                </p>
                <Button
                  text="수정"
                  large={false}
                  type="button"
                  onClick={() => setActive(true)}
                />
              </>
            )}
          </div>
          <div className={style.mypage_item}>
            <Button
              text="전체 데이터 삭제"
              type="button"
              large={true}
              onClick={handleAllContentsDelete}
            />
          </div>
        </div>
      </div>
    </>
  );
};

export default MyPage;
