import Head from "next/head";
import { Suspense } from "react";
import dynamic from "next/dynamic";

import Contents from "@components/contents/Contents";
import FormSkeleton from "@components/atomic/FormSkeleton";
const WriteForm = dynamic(() => import("@components/writeform/WriteForm"), {
  suspense: true,
});

export default function Home() {
  return (
    <>
      <Head>
        <title>돼지는 여행 중 : Pig ON Trip</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          href={`${process.env.NEXT_PUBLIC_FAVICON}/favicon.ico`}
        />
      </Head>
      <main>
        <Suspense fallback={<FormSkeleton />}>
          <WriteForm />
        </Suspense>
        <Contents />
      </main>
    </>
  );
}
