import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Pig ON Trip</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          href={`${process.env.NEXT_PUBLIC_FAVICON}/favicon.ico`}
        />
      </Head>
      <main></main>
    </>
  );
}
